[pytest]
addopts = -v -s
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO

markers =
    smoke: critical smoke tests
    regression: full regression suite
    api: API validation tests
    ui: UI automation tests
    integration: UI + API combined tests
